use std::{
    collections::{BTreeMap, BTreeSet},
    env, fs,
    path::PathBuf,
};

fn main() {
    generate_syscalls();
    generate_keymap();
    generate_assets();
    generate_palette();
    generate_settings();
    generate_vars();
    generate_sfx();
    generate_game();
    generate_player();
    generate_timing();
    generate_menu();
    generate_sprites();
    generate_animation();
    generate_rng();
    generate_render();
}

fn generate_syscalls() {
    println!("cargo:rerun-if-changed=umlang-syscalls.txt");

    let text =
        fs::read_to_string("umlang-syscalls.txt").expect("failed to read umlang-syscalls.txt");
    let mut generated = String::from("// @generated by build.rs from umlang-syscalls.txt\n");

    for raw_line in text.lines() {
        let line = raw_line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let (name, value) = line
            .split_once('=')
            .unwrap_or_else(|| panic!("invalid syscall line: {line}"));
        let name = name.trim();
        let value = value.trim();
        assert!(
            name.starts_with("SYS_")
                && name
                    .chars()
                    .all(|ch| ch.is_ascii_uppercase() || ch == '_' || ch.is_ascii_digit()),
            "invalid syscall name: {name}"
        );
        let value: i32 = value
            .parse()
            .unwrap_or_else(|_| panic!("invalid syscall value for {name}: {value}"));
        generated.push_str(&format!("pub const {name}: i32 = {value};\n"));
    }

    let out_path = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is not set"))
        .join("generated_syscalls.rs");
    fs::write(out_path, generated).expect("failed to write generated syscalls");
}

fn generate_keymap() {
    println!("cargo:rerun-if-changed=umlang-keycodes.txt");
    println!("cargo:rerun-if-changed=umlang-keymap.txt");

    let key_codes = read_keycodes();
    let text = fs::read_to_string("umlang-keymap.txt").expect("failed to read umlang-keymap.txt");
    let mut generated =
        String::from("// @generated by build.rs from umlang-keycodes.txt and umlang-keymap.txt\n");
    generated.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    generated.push_str("pub struct KeyBinding {\n");
    generated.push_str("    pub action: i32,\n");
    generated.push_str("    pub key_name: &'static str,\n");
    generated.push_str("    pub code: i32,\n");
    generated.push_str("}\n\n");

    let mut actions = BTreeSet::new();
    let mut bindings = Vec::new();

    for raw_line in text.lines() {
        let line = strip_comment(raw_line);
        if line.is_empty() {
            continue;
        }
        let (action_name, rest) = line
            .split_once('=')
            .unwrap_or_else(|| panic!("invalid keymap line: {line}"));
        let action_name = action_name.trim();
        validate_const_name(action_name, "ACTION_");
        assert!(
            actions.insert(action_name.to_string()),
            "duplicate action name: {action_name}"
        );

        let fields: Vec<_> = rest.split(',').map(str::trim).collect();
        assert!(
            fields.len() == 2,
            "invalid keymap value for {action_name}: {rest}"
        );
        let action: i32 = fields[0]
            .parse()
            .unwrap_or_else(|_| panic!("invalid action id for {action_name}: {}", fields[0]));
        let key_name = fields[1];
        validate_const_name(key_name, "KEY_");
        let code = *key_codes
            .get(key_name)
            .unwrap_or_else(|| panic!("undefined key constant for {action_name}: {key_name}"));
        bindings.push((action_name.to_string(), action, key_name.to_string(), code));
    }

    for (action_name, action, _, _) in &bindings {
        generated.push_str(&format!("pub const {action_name}: i32 = {action};\n"));
    }
    generated.push('\n');

    for (key_name, code) in &key_codes {
        generated.push_str(&format!("pub const {key_name}: i32 = {code};\n"));
    }
    generated.push_str("\npub const KEY_BINDINGS: &[KeyBinding] = &[\n");

    for (action_name, _, key_name, _) in &bindings {
        generated.push_str(&format!(
            "    KeyBinding {{ action: {action_name}, key_name: \"{key_name}\", code: {key_name} }},\n"
        ));
    }
    generated.push_str("];\n");

    let out_path =
        PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is not set")).join("generated_keymap.rs");
    fs::write(out_path, generated).expect("failed to write generated keymap");
}

fn read_keycodes() -> BTreeMap<String, i32> {
    let text =
        fs::read_to_string("umlang-keycodes.txt").expect("failed to read umlang-keycodes.txt");
    let mut key_codes = BTreeMap::new();
    for raw_line in text.lines() {
        let line = strip_comment(raw_line);
        if line.is_empty() {
            continue;
        }
        let (key_name, value) = line
            .split_once('=')
            .unwrap_or_else(|| panic!("invalid keycode line: {line}"));
        let key_name = key_name.trim();
        validate_const_name(key_name, "KEY_");
        let code: i32 = value
            .trim()
            .parse()
            .unwrap_or_else(|_| panic!("invalid keycode value for {key_name}: {value}"));
        assert!(
            key_codes.insert(key_name.to_string(), code).is_none(),
            "duplicate key constant: {key_name}"
        );
    }
    key_codes
}

fn generate_assets() {
    println!("cargo:rerun-if-changed=umlang-assets.txt");

    let values = read_key_values("umlang-assets.txt");
    let mut generated = String::from("// @generated by build.rs from umlang-assets.txt\n");

    let settings_profile = required_value(&values, "settings_profile");
    let sprite_texture = required_value(&values, "sprite_texture");
    let bgm_audio = required_value(&values, "bgm_audio");

    generated.push_str(&format!(
        "pub const SETTINGS_PROFILE: &str = {:?};\n",
        settings_profile
    ));
    generated.push_str(&format!(
        "pub const SPRITE_TEXTURE: &str = {:?};\n",
        sprite_texture
    ));
    generated.push_str(&format!("pub const BGM_AUDIO: &str = {:?};\n", bgm_audio));

    for key in [
        "sprite_texture_slot",
        "bgm_audio_slot",
        "sfx_base_slot",
        "sfx_sound_stride",
        "sfx_mode_stride",
        "sfx_mono_mode",
        "sfx_stereo_mode",
        "sfx_left_side_code",
        "sfx_center_side_code",
        "sfx_right_side_code",
    ] {
        let const_name = key.to_ascii_uppercase();
        let value = required_i32(&values, key);
        generated.push_str(&format!("pub const {const_name}: i32 = {value};\n"));
    }

    let waves = required_i32_list(&values, "sfx_waves");
    generated.push_str("\npub const SFX_WAVES: &[i32] = &[");
    for (index, wave) in waves.iter().enumerate() {
        if index > 0 {
            generated.push_str(", ");
        }
        generated.push_str(&wave.to_string());
    }
    generated.push_str("];\n");

    let out_path =
        PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is not set")).join("generated_assets.rs");
    fs::write(out_path, generated).expect("failed to write generated assets");
}

fn generate_palette() {
    println!("cargo:rerun-if-changed=umlang-palette.txt");

    let values = read_key_values("umlang-palette.txt");
    let mut colors = Vec::new();
    for (key, value) in values {
        let color_id: i32 = key
            .parse()
            .unwrap_or_else(|_| panic!("invalid palette color id: {key}"));
        let rgba = parse_i32_list_value("palette rgba", &value);
        assert!(
            rgba.len() == 4,
            "palette color {color_id} must have exactly 4 rgba values"
        );
        colors.push([color_id, rgba[0], rgba[1], rgba[2], rgba[3]]);
    }
    colors.sort_by_key(|color| color[0]);

    let mut generated = String::from("// @generated by build.rs from umlang-palette.txt\n");
    generated.push_str("pub const PALETTE: &[[i32; 5]] = &[\n");
    for [color_id, red, green, blue, alpha] in colors {
        generated.push_str(&format!(
            "    [{color_id}, {red}, {green}, {blue}, {alpha}],\n"
        ));
    }
    generated.push_str("];\n");

    let out_path = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is not set"))
        .join("generated_palette.rs");
    fs::write(out_path, generated).expect("failed to write generated palette");
}

fn generate_settings() {
    println!("cargo:rerun-if-changed=umlang-settings.txt");

    let values = read_key_values("umlang-settings.txt");
    let mut settings = Vec::new();
    for (name, value) in values {
        let fields: Vec<_> = value.split(',').map(str::trim).collect();
        assert!(
            fields.len() == 3,
            "setting {name} must be key,default,allowed_values"
        );
        let key = fields[0]
            .parse::<i32>()
            .unwrap_or_else(|_| panic!("invalid setting key for {name}: {}", fields[0]));
        let default = fields[1]
            .parse::<i32>()
            .unwrap_or_else(|_| panic!("invalid setting default for {name}: {}", fields[1]));
        let allowed =
            parse_i32_delimited_value(&format!("setting {name} allowed values"), fields[2], '|');
        assert!(
            allowed.contains(&default),
            "setting {name} default must be in allowed values"
        );
        settings.push((name, key, default, allowed));
    }
    settings.sort_by_key(|(_, key, _, _)| *key);

    let mut generated = String::from("// @generated by build.rs from umlang-settings.txt\n");
    for (name, key, default, allowed) in settings {
        let const_name = name.to_ascii_uppercase();
        generated.push_str(&format!("pub const SETTING_{const_name}: i32 = {key};\n"));
        generated.push_str(&format!(
            "pub const DEFAULT_{const_name}: i32 = {default};\n"
        ));
        generated.push_str(&format!("pub const {const_name}_VALUES: &[i32] = &["));
        for (index, value) in allowed.iter().enumerate() {
            if index > 0 {
                generated.push_str(", ");
            }
            generated.push_str(&value.to_string());
        }
        generated.push_str("];\n");
    }

    let out_path = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is not set"))
        .join("generated_settings.rs");
    fs::write(out_path, generated).expect("failed to write generated settings");
}

fn generate_vars() {
    println!("cargo:rerun-if-changed=umlang-vars.txt");

    let text = fs::read_to_string("umlang-vars.txt").expect("failed to read umlang-vars.txt");
    let mut vars = Vec::new();
    let mut seen_names = BTreeSet::new();
    let mut seen_slots = BTreeSet::new();

    for raw_line in text.lines() {
        let line = strip_comment(raw_line);
        if line.is_empty() {
            continue;
        }
        let (name, value) = line
            .split_once('=')
            .unwrap_or_else(|| panic!("invalid variable slot line: {line}"));
        let name = name.trim();
        validate_const_name(name, "");
        let slot = value
            .trim()
            .parse::<usize>()
            .unwrap_or_else(|_| panic!("invalid variable slot for {name}: {value}"));
        assert!(
            slot > 1,
            "variable slot {name} must not overlap syscall argument slots"
        );
        assert!(
            seen_names.insert(name.to_string()),
            "duplicate variable name: {name}"
        );
        assert!(seen_slots.insert(slot), "duplicate variable slot: {slot}");
        vars.push((name.to_string(), slot));
    }
    vars.sort_by_key(|(_, slot)| *slot);

    let mut generated = String::from("// @generated by build.rs from umlang-vars.txt\n");
    for (name, slot) in vars {
        generated.push_str(&format!("pub const {name}: usize = {slot};\n"));
    }

    let out_path =
        PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is not set")).join("generated_vars.rs");
    fs::write(out_path, generated).expect("failed to write generated vars");
}

fn generate_sfx() {
    println!("cargo:rerun-if-changed=umlang-sfx.txt");
    println!("cargo:rerun-if-changed=umlang-vars.txt");
    println!("cargo:rerun-if-changed=umlang-assets.txt");

    let valid_vars = read_var_name_set();
    let sfx_sound_count =
        required_i32_list(&read_key_values("umlang-assets.txt"), "sfx_waves").len();
    let text = fs::read_to_string("umlang-sfx.txt").expect("failed to read umlang-sfx.txt");
    let mut round_events = Vec::new();
    let mut ui_events = Vec::new();
    let mut jump_sound = None;
    let mut seen_flags = BTreeSet::new();

    for raw_line in text.lines() {
        let line = strip_comment(raw_line);
        if line.is_empty() {
            continue;
        }
        let (key, value) = line
            .split_once('=')
            .unwrap_or_else(|| panic!("invalid sfx line: {line}"));
        let key = key.trim();
        assert!(
            key.chars()
                .all(|ch| ch.is_ascii_lowercase() || ch.is_ascii_digit() || ch == '_'),
            "invalid sfx key: {key}"
        );

        if key.starts_with("round_event_") {
            let event = parse_sfx_event(key, value, &valid_vars, sfx_sound_count);
            assert!(
                seen_flags.insert(event.0.clone()),
                "duplicate sfx flag: {}",
                event.0
            );
            round_events.push(event);
        } else if key.starts_with("ui_event_") {
            let event = parse_sfx_event(key, value, &valid_vars, sfx_sound_count);
            assert!(
                seen_flags.insert(event.0.clone()),
                "duplicate sfx flag: {}",
                event.0
            );
            ui_events.push(event);
        } else if key == "jump_sound" {
            let fields: Vec<_> = value.split(',').map(str::trim).collect();
            assert!(fields.len() == 2, "jump_sound must be sound_id,side");
            let sound_id = parse_sfx_sound_id(key, fields[0], sfx_sound_count);
            let side = parse_fixed_sfx_side(key, fields[1]);
            assert!(
                jump_sound.replace((sound_id, side)).is_none(),
                "duplicate jump_sound"
            );
        } else {
            panic!("unknown sfx key: {key}");
        }
    }

    assert!(
        !round_events.is_empty(),
        "umlang-sfx.txt must define round SFX events"
    );
    assert!(
        !ui_events.is_empty(),
        "umlang-sfx.txt must define UI SFX events"
    );
    let (jump_sound_id, jump_side) = jump_sound.expect("umlang-sfx.txt must define jump_sound");

    let mut generated = String::from("// @generated by build.rs from umlang-sfx.txt\n");
    generated.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    generated.push_str("pub enum SfxSide {\n");
    generated.push_str("    Fixed(i32),\n");
    generated.push_str("    BallX,\n");
    generated.push_str("}\n\n");
    generated.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    generated.push_str("pub struct SfxEvent {\n");
    generated.push_str("    pub flag_name: &'static str,\n");
    generated.push_str("    pub sound_id: i32,\n");
    generated.push_str("    pub side: SfxSide,\n");
    generated.push_str("}\n\n");
    generated.push_str(&format!(
        "pub const JUMP_SOUND_ID: i32 = {jump_sound_id};\n"
    ));
    generated.push_str(&format!("pub const JUMP_SIDE: i32 = {jump_side};\n\n"));

    write_sfx_events(&mut generated, "ROUND_SFX_EVENTS", &round_events);
    generated.push('\n');
    write_sfx_events(&mut generated, "UI_SFX_EVENTS", &ui_events);

    let out_path =
        PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is not set")).join("generated_sfx.rs");
    fs::write(out_path, generated).expect("failed to write generated sfx constants");
}

fn generate_game() {
    println!("cargo:rerun-if-changed=umlang-game.txt");

    let text = fs::read_to_string("umlang-game.txt").expect("failed to read umlang-game.txt");
    let mut constants = Vec::new();
    let mut seen_names = BTreeSet::new();

    for raw_line in text.lines() {
        let line = strip_comment(raw_line);
        if line.is_empty() {
            continue;
        }
        let (name, value) = line
            .split_once('=')
            .unwrap_or_else(|| panic!("invalid game constant line: {line}"));
        let name = name.trim();
        validate_const_name(name, "");
        let value = value
            .trim()
            .parse::<i32>()
            .unwrap_or_else(|_| panic!("invalid game constant for {name}: {value}"));
        assert!(
            seen_names.insert(name.to_string()),
            "duplicate game constant name: {name}"
        );
        constants.push((name.to_string(), value));
    }

    let mut generated = String::from("// @generated by build.rs from umlang-game.txt\n");
    for (name, value) in constants {
        generated.push_str(&format!("pub const {name}: i32 = {value};\n"));
    }

    let out_path =
        PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is not set")).join("generated_game.rs");
    fs::write(out_path, generated).expect("failed to write generated game constants");
}

fn generate_timing() {
    println!("cargo:rerun-if-changed=umlang-timing.txt");

    let values = read_key_values("umlang-timing.txt");
    let mut generated = String::from("// @generated by build.rs from umlang-timing.txt\n");
    for (key, value) in values {
        let const_name = key.to_ascii_uppercase();
        let value = value
            .parse::<i32>()
            .unwrap_or_else(|_| panic!("invalid timing value for {key}: {value}"));
        assert!(value >= 0, "timing value {key} must be non-negative");
        generated.push_str(&format!("pub const {const_name}: i32 = {value};\n"));
    }

    let out_path =
        PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is not set")).join("generated_timing.rs");
    fs::write(out_path, generated).expect("failed to write generated timing constants");
}

fn generate_player() {
    println!("cargo:rerun-if-changed=umlang-player.txt");

    let values = read_key_values("umlang-player.txt");
    let mut generated = String::from("// @generated by build.rs from umlang-player.txt\n");
    for (key, value) in values {
        let const_name = key.to_ascii_uppercase();
        let value = value
            .parse::<i32>()
            .unwrap_or_else(|_| panic!("invalid player value for {key}: {value}"));
        generated.push_str(&format!("pub const {const_name}: i32 = {value};\n"));
    }

    let out_path =
        PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is not set")).join("generated_player.rs");
    fs::write(out_path, generated).expect("failed to write generated player constants");
}

fn generate_menu() {
    println!("cargo:rerun-if-changed=umlang-menu.txt");

    let values = read_key_values("umlang-menu.txt");
    let mut generated = String::from("// @generated by build.rs from umlang-menu.txt\n");
    for (key, value) in values {
        let const_name = key.to_ascii_uppercase();
        let values = parse_i32_list_value(&key, &value);
        assert!(!values.is_empty(), "menu key {key} must not be empty");
        write_i32_array(&mut generated, &const_name, &values);
    }

    let out_path =
        PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is not set")).join("generated_menu.rs");
    fs::write(out_path, generated).expect("failed to write generated menu constants");
}

fn generate_sprites() {
    println!("cargo:rerun-if-changed=umlang-sprites.txt");

    let text = fs::read_to_string("umlang-sprites.txt").expect("failed to read umlang-sprites.txt");
    let mut player_frames = BTreeMap::new();
    let mut ball_frames = BTreeMap::new();

    for raw_line in text.lines() {
        let line = strip_comment(raw_line);
        if line.is_empty() {
            continue;
        }
        let (name, value) = line
            .split_once('=')
            .unwrap_or_else(|| panic!("invalid sprite frame line: {line}"));
        let name = name.trim();
        validate_const_name(name, "");
        let rect = parse_sprite_rect(name, value.trim());

        if let Some(index) = name.strip_prefix("PLAYER_FRAME_") {
            let index = parse_frame_index("PLAYER_FRAME", index);
            assert!(
                player_frames.insert(index, rect).is_none(),
                "duplicate player frame index: {index}"
            );
        } else if let Some(index) = name.strip_prefix("BALL_FRAME_") {
            let index = parse_frame_index("BALL_FRAME", index);
            assert!(
                ball_frames.insert(index, rect).is_none(),
                "duplicate ball frame index: {index}"
            );
        } else {
            panic!("unknown sprite frame name: {name}");
        }
    }

    let player_frames = contiguous_frames("PLAYER_FRAME", player_frames);
    let ball_frames = contiguous_frames("BALL_FRAME", ball_frames);

    let mut generated = String::from("// @generated by build.rs from umlang-sprites.txt\n");
    write_frame_array(&mut generated, "PLAYER_FRAMES", &player_frames);
    generated.push('\n');
    write_frame_array(&mut generated, "BALL_FRAMES", &ball_frames);

    let out_path = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is not set"))
        .join("generated_sprites.rs");
    fs::write(out_path, generated).expect("failed to write generated sprite frames");
}

fn generate_animation() {
    println!("cargo:rerun-if-changed=umlang-animation.txt");

    let values = read_key_values("umlang-animation.txt");
    let mut anim_rules = BTreeMap::new();
    let mut draw_states = BTreeMap::new();

    for (key, value) in values {
        if let Some(index) = key.strip_prefix("player_anim_state_") {
            let state = parse_frame_index("player_anim_state", index) as i32;
            let values = parse_i32_list_value(&key, &value);
            assert!(
                values.len() == 2,
                "{key} must be frame_counter_divisor,frame_modulo"
            );
            assert!(
                values[0] > 0 && values[1] > 0,
                "{key} values must be positive"
            );
            assert!(
                anim_rules.insert(state, [values[0], values[1]]).is_none(),
                "duplicate player anim state: {state}"
            );
        } else if let Some(index) = key.strip_prefix("player_draw_state_") {
            let state = parse_frame_index("player_draw_state", index) as i32;
            let values = parse_i32_list_value(&key, &value);
            assert!(
                !values.is_empty(),
                "{key} must list at least one sprite index"
            );
            assert!(
                values.iter().all(|value| *value >= 0),
                "{key} sprite indices must be non-negative"
            );
            assert!(
                draw_states.insert(state, values).is_none(),
                "duplicate player draw state: {state}"
            );
        } else {
            panic!("unknown animation key: {key}");
        }
    }

    assert!(
        !anim_rules.is_empty(),
        "umlang-animation.txt must define player animation states"
    );
    assert!(
        !draw_states.is_empty(),
        "umlang-animation.txt must define player draw states"
    );

    let mut generated = String::from("// @generated by build.rs from umlang-animation.txt\n");
    generated.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    generated.push_str("pub struct PlayerAnimRule {\n");
    generated.push_str("    pub state: i32,\n");
    generated.push_str("    pub frame_divisor: i32,\n");
    generated.push_str("    pub frame_modulo: i32,\n");
    generated.push_str("}\n\n");
    generated.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    generated.push_str("pub struct PlayerDrawState {\n");
    generated.push_str("    pub state: i32,\n");
    generated.push_str("    pub sprite_indices: &'static [usize],\n");
    generated.push_str("}\n\n");

    generated.push_str("pub const PLAYER_ANIM_RULES: &[PlayerAnimRule] = &[\n");
    for (state, [frame_divisor, frame_modulo]) in &anim_rules {
        generated.push_str(&format!(
            "    PlayerAnimRule {{ state: {state}, frame_divisor: {frame_divisor}, frame_modulo: {frame_modulo} }},\n"
        ));
    }
    generated.push_str("];\n\n");

    for (state, sprite_indices) in &draw_states {
        generated.push_str(&format!(
            "pub const PLAYER_DRAW_STATE_{state}: &[usize] = &["
        ));
        for (index, sprite_index) in sprite_indices.iter().enumerate() {
            if index > 0 {
                generated.push_str(", ");
            }
            generated.push_str(&sprite_index.to_string());
        }
        generated.push_str("];\n");
    }
    generated.push_str("\npub const PLAYER_DRAW_STATES: &[PlayerDrawState] = &[\n");
    for state in draw_states.keys() {
        generated.push_str(&format!(
            "    PlayerDrawState {{ state: {state}, sprite_indices: PLAYER_DRAW_STATE_{state} }},\n"
        ));
    }
    generated.push_str("];\n");

    let out_path = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is not set"))
        .join("generated_animation.rs");
    fs::write(out_path, generated).expect("failed to write generated animation constants");
}

fn generate_rng() {
    println!("cargo:rerun-if-changed=umlang-rng.txt");

    let values = read_key_values("umlang-rng.txt");
    let seed_bytes = required_byte_list(&values, "seed_bytes");
    let multiplier_bytes = required_byte_list(&values, "multiplier_bytes");
    assert!(
        seed_bytes.len() == 8,
        "seed_bytes must contain exactly 8 bytes"
    );
    assert!(
        multiplier_bytes.len() == 8,
        "multiplier_bytes must contain exactly 8 bytes"
    );

    let mut generated = String::from("// @generated by build.rs from umlang-rng.txt\n");
    write_i32_array(&mut generated, "RNG_SEED_BYTES", &seed_bytes);
    generated.push('\n');
    write_i32_array(&mut generated, "RNG_MULTIPLIER_BYTES", &multiplier_bytes);

    let out_path =
        PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is not set")).join("generated_rng.rs");
    fs::write(out_path, generated).expect("failed to write generated rng constants");
}

fn generate_render() {
    println!("cargo:rerun-if-changed=umlang-render.txt");

    let values = read_key_values("umlang-render.txt");
    let mut generated = String::from("// @generated by build.rs from umlang-render.txt\n");
    for (key, value) in values {
        let const_name = key.to_ascii_uppercase();
        let values = parse_i32_list_value(&key, &value);
        assert!(!values.is_empty(), "render key {key} must not be empty");
        write_i32_array(&mut generated, &const_name, &values);
    }

    let out_path =
        PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is not set")).join("generated_render.rs");
    fs::write(out_path, generated).expect("failed to write generated render constants");
}

fn read_var_name_set() -> BTreeSet<String> {
    let text = fs::read_to_string("umlang-vars.txt").expect("failed to read umlang-vars.txt");
    let mut names = BTreeSet::new();
    for raw_line in text.lines() {
        let line = strip_comment(raw_line);
        if line.is_empty() {
            continue;
        }
        let (name, _) = line
            .split_once('=')
            .unwrap_or_else(|| panic!("invalid variable slot line: {line}"));
        let name = name.trim();
        validate_const_name(name, "");
        names.insert(name.to_string());
    }
    names
}

fn parse_sfx_event(
    key: &str,
    value: &str,
    valid_vars: &BTreeSet<String>,
    sfx_sound_count: usize,
) -> (String, i32, String) {
    let fields: Vec<_> = value.split(',').map(str::trim).collect();
    assert!(
        fields.len() == 3,
        "{key} must be flag_variable,sound_id,side"
    );
    let flag_name = fields[0];
    validate_const_name(flag_name, "");
    assert!(
        valid_vars.contains(flag_name),
        "{key} references unknown variable flag: {flag_name}"
    );
    let sound_id = parse_sfx_sound_id(key, fields[1], sfx_sound_count);
    let side = parse_sfx_side(key, fields[2]);
    (flag_name.to_string(), sound_id, side)
}

fn parse_sfx_sound_id(key: &str, value: &str, sfx_sound_count: usize) -> i32 {
    let sound_id = value
        .parse::<i32>()
        .unwrap_or_else(|_| panic!("invalid sound id for {key}: {value}"));
    assert!(
        sound_id > 0 && sound_id <= sfx_sound_count as i32,
        "{key} sound id {sound_id} must be within the SFX wave bank"
    );
    sound_id
}

fn parse_fixed_sfx_side(key: &str, value: &str) -> i32 {
    let side = value
        .parse::<i32>()
        .unwrap_or_else(|_| panic!("invalid fixed SFX side for {key}: {value}"));
    assert!(
        (-1..=1).contains(&side),
        "{key} fixed SFX side must be -1, 0, or 1"
    );
    side
}

fn parse_sfx_side(key: &str, value: &str) -> String {
    if value == "ball_x" {
        return "SfxSide::BallX".to_string();
    }
    format!("SfxSide::Fixed({})", parse_fixed_sfx_side(key, value))
}

fn write_sfx_events(generated: &mut String, name: &str, events: &[(String, i32, String)]) {
    generated.push_str(&format!("pub const {name}: &[SfxEvent] = &[\n"));
    for (flag_name, sound_id, side) in events {
        generated.push_str(&format!(
            "    SfxEvent {{ flag_name: {:?}, sound_id: {sound_id}, side: {side} }},\n",
            flag_name
        ));
    }
    generated.push_str("];\n");
}

fn parse_sprite_rect(name: &str, value: &str) -> [i32; 4] {
    let values = parse_i32_list_value(name, value);
    assert!(
        values.len() == 4,
        "sprite frame {name} must have exactly 4 values"
    );
    [values[0], values[1], values[2], values[3]]
}

fn parse_frame_index(kind: &str, value: &str) -> usize {
    value
        .parse()
        .unwrap_or_else(|_| panic!("invalid {kind} index: {value}"))
}

fn contiguous_frames(kind: &str, frames: BTreeMap<usize, [i32; 4]>) -> Vec<[i32; 4]> {
    assert!(!frames.is_empty(), "{kind} must define at least one frame");
    let mut values = Vec::new();
    for (expected, (index, frame)) in frames.into_iter().enumerate() {
        assert!(
            index == expected,
            "{kind} frame indices must be contiguous from 0; missing {expected}"
        );
        values.push(frame);
    }
    values
}

fn write_frame_array(generated: &mut String, name: &str, frames: &[[i32; 4]]) {
    generated.push_str(&format!("pub const {name}: &[[i32; 4]] = &[\n"));
    for [sx, sy, sw, sh] in frames {
        generated.push_str(&format!("    [{sx}, {sy}, {sw}, {sh}],\n"));
    }
    generated.push_str("];\n");
}

fn read_key_values(path: &str) -> BTreeMap<String, String> {
    let text =
        fs::read_to_string(path).unwrap_or_else(|err| panic!("failed to read {path}: {err}"));
    let mut values = BTreeMap::new();
    for raw_line in text.lines() {
        let line = strip_comment(raw_line);
        if line.is_empty() {
            continue;
        }
        let (key, value) = line
            .split_once('=')
            .unwrap_or_else(|| panic!("invalid key/value line in {path}: {line}"));
        let key = key.trim();
        assert!(
            key.chars()
                .all(|ch| ch.is_ascii_lowercase() || ch.is_ascii_digit() || ch == '_'),
            "invalid key in {path}: {key}"
        );
        assert!(
            values
                .insert(key.to_string(), value.trim().to_string())
                .is_none(),
            "duplicate key in {path}: {key}"
        );
    }
    values
}

fn required_value<'a>(values: &'a BTreeMap<String, String>, key: &str) -> &'a str {
    values
        .get(key)
        .map(String::as_str)
        .filter(|value| !value.is_empty())
        .unwrap_or_else(|| panic!("missing required asset key: {key}"))
}

fn required_i32(values: &BTreeMap<String, String>, key: &str) -> i32 {
    required_value(values, key)
        .parse()
        .unwrap_or_else(|_| panic!("invalid i32 asset value for {key}"))
}

fn required_i32_list(values: &BTreeMap<String, String>, key: &str) -> Vec<i32> {
    let values = parse_i32_list_value(key, required_value(values, key));
    assert!(!values.is_empty(), "empty i32 list asset value for {key}");
    values
}

fn required_byte_list(values: &BTreeMap<String, String>, key: &str) -> Vec<i32> {
    let values = required_i32_list(values, key);
    for value in &values {
        assert!(
            (0..=255).contains(value),
            "{key} values must be bytes, got {value}"
        );
    }
    values
}

fn parse_i32_list_value(context: &str, value: &str) -> Vec<i32> {
    parse_i32_delimited_value(context, value, ',')
}

fn parse_i32_delimited_value(context: &str, value: &str, delimiter: char) -> Vec<i32> {
    value
        .split(delimiter)
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .map(|value| {
            value
                .parse()
                .unwrap_or_else(|_| panic!("invalid i32 list item for {context}: {value}"))
        })
        .collect()
}

fn strip_comment(line: &str) -> &str {
    line.split_once('#')
        .map_or(line, |(before, _)| before)
        .trim()
}

fn validate_const_name(name: &str, prefix: &str) {
    assert!(
        name.starts_with(prefix)
            && name
                .chars()
                .all(|ch| ch.is_ascii_uppercase() || ch.is_ascii_digit() || ch == '_'),
        "invalid constant name: {name}"
    );
}

fn write_i32_array(generated: &mut String, name: &str, values: &[i32]) {
    generated.push_str(&format!("pub const {name}: &[i32] = &["));
    for (index, value) in values.iter().enumerate() {
        if index > 0 {
            generated.push_str(", ");
        }
        generated.push_str(&value.to_string());
    }
    generated.push_str("];\n");
}
